name: wiam-test-job

volumes:
  site-db:

services:
  nginx:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - .:/web-app:ro
      - ./docker/site.conf:/etc/nginx/conf.d/default.conf:ro
    working_dir: /web-app
    depends_on:
      - php

  php:
    build:
      context: ./docker
      dockerfile: php-docker.file
      args: {}
        # mode: production
      # admin_token: ${admin_token:-xyz123}
    command: 'sh ./docker/deploy.sh'
    volumes:
      - .:/web-app
    working_dir: /web-app
    user: ${user_id}:${user_id}
    depends_on:
      - db

  db:
    image: postgres:alpine
    volumes:
      - site-db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${db_pass:-wiam-test}
      POSTGRES_USER: ${db_user:-wiam-test}
      POSTGRES_DB: ${db_name:-wiam-test}



